[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
auto_detect_solc = false
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 3

# RPC endpoints for different networks
[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
bsc = "${BSC_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

# Etherscan API keys for verification (v2 supports 50+ chains)
[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${ETHERSCAN_API_KEY}" }
amoy = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${ETHERSCAN_API_KEY}" }
avalanche = { key = "${ETHERSCAN_API_KEY}" }

# Gas settings for different networks
[profile.gas_reports]
ethereum = { price = 20, priority = 2 }
polygon = { price = 30, priority = 30 }
bsc = { price = 3, priority = 1 }

# Deployment configurations
[profile.deployment]
ethereum = { private_key = "${PRIVATE_KEY}", gas_limit = 5000000 }
polygon = { private_key = "${PRIVATE_KEY}", gas_limit = 5000000 }
mumbai = { private_key = "${PRIVATE_KEY}", gas_limit = 5000000 }
bsc = { private_key = "${PRIVATE_KEY}", gas_limit = 5000000 }
avalanche = { private_key = "${PRIVATE_KEY}", gas_limit = 5000000 }
